---
title: "Lab1"
author: "Jo Starenky"
date: "2024-09-16"
output: "github_document"
---

# Load Packages
```{r}

library(haven)
library(tidyr)
library(ggplot2)
library(datasauRus)
library(dplyr)
```

# First look of descriptive statistics 
```{r}

datasaurus_dozen %>% 
  group_by(dataset) %>%
  dplyr::summarize(mean_x    = mean(x),
      mean_y    = mean(y),
      std_dev_x = sd(x),
      std_dev_y = sd(y),
      corr_x_y  = cor(x, y)
    )


```

# Introduce GGplot
```{r}

ggplot(datasaurus_dozen, aes(x = x, y = y, colour = dataset))+
    geom_point() + facet_wrap(~dataset)

dino<- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(dino, aes(x = x, y = y))+
  geom_point (color="#FF13F0") + theme_void() + labs(title = "Hi, I'm a dino!") + theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 20, color = "pink"))




```


# Q1: What is the function of facet wrap? In what situation do you think you will use this function? 




# Q2: The means, standard deviations, and correlations are pretty much the same, but the data pattern looks very different for each dataset. What is the implication here? 

